Input Test
Symmetrics-Lab/react-ui pull request #2
Opened 2022-10-26 13:43 UTC by elipierrotnoxiii

2022-10-26 13:56 UTC, oliversd requested changes

2022-10-26 13:56 UTC, oliversd commented on library/src/components/Input/input.test.tsx
> +  test('pass invalid name to test name input field', () => {
Este test es incorrecto, tu estas forzando la clase cuando creas el input por lo que siempre va a tener la clase de error. También un espacio en blanco no es un input inválido

2022-10-26 13:56 UTC, oliversd commented on library/src/components/Input/input.test.tsx
> +  test('render lastname text input', () => {
Este test es lo mismo que el primero y es innecesario

2022-10-26 13:56 UTC, oliversd commented on library/src/components/Input/input.test.tsx
> +  test('pass valid lastname to test lastname input field', () => {
Mismo test que hiciste con el name, es innecesario

2022-10-26 13:56 UTC, oliversd commented on library/src/components/Input/input.test.tsx
> +  test('pass invalid lastname to test lastname input field', () => {
Mismo problema de arriba, si le pasas la clase cuando lo creas va a tener la clase al final

2022-10-26 13:56 UTC, oliversd commented on library/src/components/Input/input.test.tsx
> +  test('pass valid email to test email input field', () => {
Mismo problema clase de error cuando lo creas y después lees la clase.

2022-10-26 13:57 UTC, elipierrotnoxiii commented on library/src/components/Input/input.test.tsx
> +  test('pass valid email to test email input field', () => {
okay

2022-10-28 12:24 UTC, oliversd requested changes

2022-10-28 12:24 UTC, oliversd commented on library/src/components/Label/Label.test.tsx
> +    expect(screen.getByTestId('test').getAttribute('require'));
Aqui no estas probando nada estas tomando un atributo nada más

2022-10-28 12:24 UTC, oliversd commented on library/src/components/Label/Label.test.tsx
> +    expect(screen.getByTestId('test').getAttribute('disable'));
Aquí no estás probando nada estás tomando un atributo nada más.

2022-10-28 12:24 UTC, oliversd commented on library/src/components/Label/Label.test.tsx
> +    expect(screen.getByTestId('test').getAttribute('hidden'));
No se está probando nada

2022-10-28 12:24 UTC, oliversd commented on library/src/components/Label/Label.test.tsx
> +describe('Label', () => {
Para Label faltan las pruebas de required y hint si te fijas en el código del componente para required se agrega un span con una clase y un ***** y para hint se agrega un span con una clase y el hint que se pasa.

``js
{required && (
          <span className="sym-textfield__required_label text-red-700" aria-label="required">
            *
          </span>
        )}
      </label>
      {hint && (
        <span className="sym-textfield__hint text-sm text-gray-500" id={`${id}-hint`}>
          {hint}
        </span>
      )}
```

2022-11-03 13:28 UTC, merged